name: sleepy-stack-example

services:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      retries: 15
      timeout: 3s
      interval: 2s
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
